"""Hand-made passage links for picture collections whose Commons titles don't carry a
reference (Gustave Doré's Bible plates, James Tissot's Life of Christ). Keys are the
pictures' titles; values are references in ordinary notation. pictures_build.py checks
every one against the bundled Bible (the chapter must exist, and words from the title must
appear in that chapter) and prints any that don't look right for review.

Scenes from the Apocrypha, later church tradition (e.g. Veronica's veil), portraits and
landscapes have no entry and are left out of the catalogue.
"""

DORE_REFS = {
    "The Creation of Light": "Genesis 1:3",
    "The Creation of Eve": "Genesis 2:21-22",
    "Adam and Eve Are Driven out of Eden": "Genesis 3:23-24",
    "Cain and Abel Offer Their Sacrifices": "Genesis 4:3-4",
    "Cain Slays Abel": "Genesis 4:8",
    "The World Is Destroyed by Water": "Genesis 7:17-23",
    "The Great Flood": "Genesis 7:21-23",
    "A Dove Is Sent Forth from the Ark": "Genesis 8:8-12",
    "Noah Curses Ham and Canaan": "Genesis 9:24-25",
    "The Tower of Babel": "Genesis 11:4-9",
    "Abraham Goes to the Land of Canaan": "Genesis 12:5",
    "Abraham and the Three Angels": "Genesis 18:1-2",
    "Lot Flees as Sodom and Gomorrah Burn": "Genesis 19:24-26",
    "Abraham Sends Hagar and Ishmael Away": "Genesis 21:14",
    "Hagar and Ishmael in the Wilderness": "Genesis 21:15-19",
    "The Testing of Abraham's Faith": "Genesis 22:9-12",
    "The Burial of Sarah": "Genesis 23:19",
    "Eliezer and Rebekah at the Well": "Genesis 24:15-20",
    "The Meeting of Isaac and Rebekah": "Genesis 24:63-67",
    "Isaac Blesses Jacob": "Genesis 27:26-29",
    "Jacob's Dream": "Genesis 28:12",
    "Jacob Tends Laban's Flocks and Meets Rachel": "Genesis 29:9-11",
    "Jacob Prays for Protection": "Genesis 32:9-12",
    "Jacob Wrestles with the Angel": "Genesis 32:24-30",
    "Jacob and Esau Meet": "Genesis 33:4",
    "Joseph Is Sold by His Brothers": "Genesis 37:28",
    "Joseph Interprets Pharaoh's Dream": "Genesis 41:25",
    "Joseph Reveals Himself to His Brothers": "Genesis 45:1-4",
    "Jacob Goes to Egypt": "Genesis 46:5-7",
    "The Child Moses on the Nile": "Exodus 2:3",
    "The Finding of Moses": "Exodus 2:5-6",
    "Moses and Aaron Appear before Pharaoh": "Exodus 7:10",
    "The Fifth Plague. Livestock Disease": "Exodus 9:3-6",
    "The Ninth Plague. Darkness": "Exodus 10:21-23",
    "The Firstborn of the Egyptians Are Slain": "Exodus 12:29",
    "The Egyptians Ask Moses to Depart": "Exodus 12:31-33",
    "The Egyptians Drown in the Sea": "Exodus 14:27-28",
    "The Giving of the Law on Mount Sinai": "Exodus 19:16-20",
    "Moses Comes Down from Mount Sinai": "Exodus 34:29",
    "The Death of Korah, Dathan, and Abiram": "Numbers 16:31-33",
    "Moses Strikes the Rock at Horeb": "Exodus 17:6",
    "Moses Breaks the Tables of the Law": "Exodus 32:19",
    "The Spies Return from the Promised Land": "Numbers 13:23-27",
    "The Bronze Serpent": "Numbers 21:8-9",
    "An Angel Appears to Balaam": "Numbers 22:31",
    "The Israelites Cross the Jordan River": "Joshua 3:14-17",
    "An Angel Appears to the Israelites": "Judges 2:1-4",
    "The Walls of Jericho Fall Down": "Joshua 6:20",
    "Joshua Spares Rahab": "Joshua 6:22-25",
    "Achan Is Stoned to Death": "Joshua 7:24-26",
    "Joshua Burns the Town of Ai": "Joshua 8:19-28",
    "The Army of the Amorites Is Destroyed": "Joshua 10:10-11",
    "Joshua Commands the Sun to Stand Still": "Joshua 10:12-13",
    "Jael Kills Sisera": "Judges 4:21",
    "Deborah Praises Jael": "Judges 5:24-27",
    "Gideon Chooses 300 Soldiers": "Judges 7:5-7",
    "The Midianites Are Routed": "Judges 7:19-22",
    "The Death of Gideon's Sons": "Judges 9:5",
    "The Death of Abimelech": "Judges 9:53-54",
    "Jephthah's Daughter Comes to Meet Her Father": "Judges 11:34",
    "Israelite Women Mourn with Jephthah's Daughter": "Judges 11:37-40",
    "Samson Slays a Lion": "Judges 14:5-6",
    "Samson Destroys the Philistines with an Ass' Jawbone": "Judges 15:15",
    "Samson Carries away the Gates of Gaza": "Judges 16:3",
    "Samson and Delilah": "Judges 16:19",
    "The Death of Samson": "Judges 16:29-30",
    "A Levite Finds a Woman's Corpse": "Judges 19:27",
    "The Levite Carries the Woman's Body Away": "Judges 19:28",
    "The Benjaminites Take the Virgins of Jabesh-gilead": "Judges 21:12-14",
    "Naomi and Her Daughters-in-Law": "Ruth 1:14",
    "Ruth and Boaz": "Ruth 2:8",
    "The Ark Is Returned to Beth-shemesh": "1 Samuel 6:13",
    "Samuel Blesses Saul": "1 Samuel 10:1",
    "The Death of Agag": "1 Samuel 15:32-33",
    "David Slays Goliath": "1 Samuel 17:49-51",
    "Saul Attempts to Kill David": "1 Samuel 18:10-11",
    "David Escapes through a Window": "1 Samuel 19:12",
    "David and Jonathan": "1 Samuel 20:41",
    "David Shows Saul How He Spared His Life": "1 Samuel 26:13-16",
    "Saul and the Witch of Endor": "1 Samuel 28:12-14",
    "The Death of Saul": "1 Samuel 31:4",
    "Jabesh-Gileadites Recover the Bodies of Saul and His Sons": "1 Samuel 31:11-13",
    "Combat between Soldiers of Ish-bosheth and David": "2 Samuel 2:15-16",
    "David Attacks the Ammonites": "2 Samuel 12:29-31",
    "The Death of Absalom": "2 Samuel 18:9-14",
    "David Mourns the Death of Absalom": "2 Samuel 18:33",
    "Rizpah’s Kindness toward the Dead": "2 Samuel 21:10",
    "Abishai Saves David's Life": "2 Samuel 21:16-17",
    "The Judgment of Solomon": "1 Kings 3:24-27",
    "Cedars Are Cut Down for the Jerusalem Temple": "1 Kings 5:6-10",
    "Solomon Receives the Queen of Sheba": "1 Kings 10:1-2",
    "King Solomon in Old Age": "1 Kings 11:4",
    "The Disobedient Prophet Is Slain by a Lion": "1 Kings 13:24",
    "Elijah Raises the Son of the Widow of Zarephath": "1 Kings 17:22-23",
    "The Prophets of Baal Are Slaughtered": "1 Kings 18:40",
    "Elijah Is Nourished by an Angel": "1 Kings 19:5-7",
    "The Israelites Slaughter the Syrians": "1 Kings 20:29",
    "The Death of Ahab": "1 Kings 22:34-35",
    "Elijah Destroys the Messengers of Ahaziah": "2 Kings 1:10-12",
    "Elijah Ascends to Heaven in a Chariot of Fire": "2 Kings 2:11",
    "Some Children Are Destroyed by Bears": "2 Kings 2:23-24",
    "A Famine in Samaria": "2 Kings 6:25",
    "The Death of Jezebel": "2 Kings 9:33",
    "Jehu's Companions Find Jezebel's Remains": "2 Kings 9:35",
    "The Death of Athaliah": "2 Kings 11:16",
    "Foreign Nations Are Slain by Lions in Samaria": "2 Kings 17:25",
    "Sennacherib's Army Is Destroyed": "2 Kings 19:35",
    "Zedekiah's Sons Are Slaughtered before His Eyes": "2 Kings 25:7",
    "The Plague of Jerusalem": "2 Samuel 24:15-16",
    "The Ammonite and Moabite Armies Are Destroyed": "2 Chronicles 20:22-23",
    "Cyrus Restores the Vessels of the Temple": "Ezra 1:7",
    "The Rebuilding of the Temple Is Begun": "Ezra 3:10",
    "Artaxerxes Grants Freedom to the Jews": "Ezra 7:11-13",
    "Ezra Kneels in Prayer": "Ezra 9:5",
    "Nehemiah Views the Ruins of Jerusalem's Walls": "Nehemiah 2:13-15",
    "Ezra Reads the Law to the People": "Nehemiah 8:2-3",
    "Queen Vashti Refuses to Obey Ahasuerus' Command": "Esther 1:12",
    "Esther Before the King": "Esther 5:1-2",
    "The Triumph of Mordecai": "Esther 6:11",
    "Esther Accuses Haman": "Esther 7:6",
    "Job Hears of His Misfortunes": "Job 1:13-20",
    "Job Speaks with His Friends": "Job 2:11-13",
    "The Prophet Isaiah": "Isaiah 1:1",
    "Isaiah's Vision of the Destruction of Babylon": "Isaiah 13:19-22",
    "The Destruction of Leviathan": "Isaiah 27:1",
    "Baruch Writes Jeremiah's Prophecies": "Jeremiah 36:4",
    "The Prophet Jeremiah": "Jeremiah 1:1",
    "People Mourn over the Destruction of Jerusalem": "Lamentations 1:1",
    "The Prophet Ezekiel": "Ezekiel 1:1",
    "Daniel among the Exiles": "Daniel 1:6",
    "Shadrach, Meshach and Abednego in the Furnace": "Daniel 3:23-25",
    "Daniel Interprets the Writing on the Wall": "Daniel 5:25-28",
    "Daniel in the Lions' Den": "Daniel 6:22",
    "Daniel's Vision of the Four Beasts": "Daniel 7:3",
    "The Prophet Amos": "Amos 1:1",
    "Jonah Is Spewed Forth by the Whale": "Jonah 2:10",
    "Jonah Preaches to the Ninevites": "Jonah 3:4",
    "Micah Exhorts the Israelites to Repent": "Micah 6:1-8",
    "Zechariah's Vision of Four Chariots": "Zechariah 6:1",
}

TISSOT_NT_REFS = {
    '"I Thirst" The Vinegar Given to Jesus': "John 19:28-29",
    "A Woman Cries Out in a Crowd": "Luke 11:27",
    "Address to Saint Philip": "John 14:8-9",
    "Agnus-Dei The Scapegoat": "Leviticus 16:21-22",
    "All the City Was Gathered at His Door": "Mark 1:33",
    "Annas and Caiaphas": "John 18:13",
    "Apparition of Our Lord to Saint Peter": "Luke 24:34",
    "Baptism of Jesus by Tissot": "Matthew 3:16",
    "Barabbas": "Matthew 27:16",
    "Behold the Man": "John 19:5",
    "Bird's-Eye View of the Forum Jesus Hears His Death Sentence": "John 19:13-16",
    "But No Man Laid Hands Upon Him": "John 7:30",
    "Christ Appears on the Shore of Lake Tiberias": "John 21:4",
    "Christ Retreats to the Mountain at Night": "Luke 21:37",
    "Conspiracy of the Jews": "Matthew 26:3-4",
    "Curses Against the Pharisees": "Matthew 23:13",
    "Feed My Lambs": "John 21:15",
    "Get Thee Behind Me Satan": "Matthew 16:23",
    "He Did No Miracles But He Healed Them": "Mark 6:5",
    "He Heals the Lame": "Matthew 15:30",
    "He Sent them out Two by Two": "Mark 6:7",
    "He Vanished from Their Sight": "Luke 24:31",
    "He Went Through the Villages on the Way to Jerusalem": "Luke 13:22",
    "He Went on His Way to Ephraim": "John 11:54",
    "He Who Winnows His Wheat": "Matthew 3:12",
    "He Who is of God Hears the Word of God": "John 8:47",
    "HealWomanSabbath": "Luke 13:12-13",
    "Healing of the Lepers at Capernaum": "Matthew 8:2-3",
    "In the Villages the Sick Were Presented to Him": "Mark 6:56",
    "Interview between Jesus and Nicodemus": "John 3:1-2",
    "It Is Finished": "John 19:30",
    "James Tissot Jesus Ministered to by Angels": "Matthew 4:11",
    "Jerusalem Jerusalem": "Matthew 23:37",
    "Jesus Alone on the Cross": "Luke 23:33",
    "Jesus Among the Doctors": "Luke 2:46",
    "Jesus Appears to Mary Magdalene": "John 20:14-16",
    "Jesus Appears to the Holy Women": "Matthew 28:9",
    "Jesus Bearing the Cross": "John 19:17",
    "Jesus Before Herod": "Luke 23:8-9",
    "Jesus Before Pilate First Interview.": "John 18:33",
    "Jesus Before Pilate Second Interview": "John 19:9",
    "Jesus Carried to the Tomb": "John 19:41-42",
    "Jesus Carried up to a Pinnacle of the Temple": "Matthew 4:5",
    "Jesus Chases a Possessed Man from the Synagogue": "Mark 1:25-26",
    "Jesus Commands the Apostles to Rest": "Mark 6:31",
    "Jesus Discourses with His Disciples": "John 14:1",
    "Jesus Forbids the Carrying of Loads in the Forecourt of the Temple": "Mark 11:16",
    "Jesus Found in the Temple": "Luke 2:46",
    "Jesus Goes Up Alone onto a Mountain to Pray": "Matthew 14:23",
    "Jesus Goes in the Evening to Bethany": "Mark 11:11",
    "Jesus Heals a Mute Possessed Man": "Matthew 9:32-33",
    "Jesus Heals the Blind and Lame on the Mountain": "Matthew 15:30",
    "Jesus Leaves the Praetorium": "John 19:16",
    "Jesus Led from Caiaphas to Pilate": "John 18:28",
    "Jesus Led from Herod to Pilate": "Luke 23:11",
    "Jesus Mary Magdalene and Martha at Bethany": "Luke 10:38-39",
    "Jesus Ministered to by Angels": "Matthew 4:11",
    "Jesus Preaches in a Ship": "Luke 5:3",
    "Jesus Sits by the Seashore and Preaches": "Matthew 13:1-2",
    "Jesus Sleeping During the Tempest": "Mark 4:38",
    "Jesus Speaks Near the Treasury": "John 8:20",
    "Jesus Stilling the Tempest": "Mark 4:39",
    "Jesus Stripped of His Clothing": "John 19:23",
    "Jesus Teaches in the Synagogues": "Matthew 4:23",
    "Jesus Teaches the People by the Sea": "Mark 4:1",
    "Jesus Teaching on the Sea-Shore": "Mark 4:1",
    "Jesus Tempted in the Wilderness": "Matthew 4:1",
    "Jesus Transported by a Spirit onto a High Mountain": "Matthew 4:8",
    "Jesus Unrolls the Book in the Synagogue": "Luke 4:17",
    "Jesus Walks in the Portico of Solomon": "John 10:23",
    "Jesus Walks on the Sea": "Matthew 14:25",
    "Jesus Went Out into a Desert Place": "Mark 1:35",
    "Jesus Wept": "John 11:35",
    "Jesus and the Little Child": "Matthew 18:2",
    "Jesus in the Sepulchre": "John 19:41-42",
    "Joseph of Arimathaea": "Matthew 27:57",
    "Joseph of Arimathaea Seeks Pilate to Beg Permission to Remove the Body of Jesus": "Mark 15:43",
    "Judas Goes to Find the Jews": "Matthew 26:14-15",
    "Judas Hangs Himself": "Matthew 27:5",
    "Judas Leaves the Cenacle": "John 13:30",
    "Judas Returns the Money": "Matthew 27:3",
    "Le possédé au pied du Thabor": "Mark 9:20",
    "Let Him Be Crucified": "Matthew 27:22",
    "Lord, I Am Not Worthy": "Matthew 8:8",
    "Magi tissot": "Matthew 2:1",
    "Maltreatments in the House of Caiaphas": "Matthew 26:67",
    "Mary Magdalene Questions the Angels in the Tomb": "John 20:12-13",
    "Mary Magdalene and the Holy Women at the Tomb": "Mark 16:1-2",
    "Mary Magdalene at the Feet of Jesus": "Luke 7:38",
    "Meal of Our Lord and the Apostles": "Luke 22:14",
    "My God My God why hast thou forsaken me": "Matthew 27:46",
    "My Name is Legion": "Mark 5:9",
    "My Soul is Sorrowful unto Death": "Matthew 26:38",
    "Nathaniel Under the Fig Tree": "John 1:48",
    "Nicodemus": "John 3:1",
    "On Entering the House, Salute It": "Matthew 10:12",
    "On Return from Jerusalem, It is Noticed that Jesus is Lost": "Luke 2:43-44",
    "Ordaining of the Twelve Apostles": "Mark 3:14",
    "Pilate Washes His Hands": "Matthew 27:24",
    "Portrait of Zacharias and Elizabeth": "Luke 1:5-6",
    "Saint John the Baptist Sees Jesus from Afar": "John 1:29",
    "Saint John the Baptist and the Pharisees": "Matthew 3:7",
    "Saint Joseph Seeks a Lodging in Bethlehem": "Luke 2:4-7",
    "Saint Peter Alerted by Saint John to the Presence of the Lord Casts Himself into the Water": "John 21:7",
    "Saint Peter Walks on the Sea": "Matthew 14:29",
    "Saint Peter and Saint John Follow from Afar": "John 18:15",
    "Saint Peter and Saint John Run to the Sepulchre": "John 20:3-4",
    "Simon the Cyrenian Compelled to Carry the Cross with Jesus": "Luke 23:26",
    "Simon the Cyrenian and His Two Sons Alexander and Rufus": "Mark 15:21",
    "Suffer the Little Children to Come unto Me": "Mark 10:14",
    "The Accursed Fig Tree": "Mark 11:20-21",
    "The Adoration of the Magi": "Matthew 2:11",
    "The Adoration of the Shepherds": "Luke 2:16",
    "The Adulterous Woman Alone with Jesus": "John 8:9",
    "The Adulterous Woman--Christ Writing upon the Ground": "John 8:6",
    "The Aged Simeon": "Luke 2:28",
    "The Angel Seated on the Stone of the Tomb": "Matthew 28:2",
    "The Angel and the Shepherds": "Luke 2:9",
    "The Annunciation": "Luke 1:28",
    "The Anxiety of Saint Joseph": "Matthew 1:19",
    "The Appearance of Christ at the Cenacle": "John 20:19",
    "The Ascension": "Acts 1:9",
    "The Axe in the Trunk of the Tree": "Matthew 3:10",
    "The Bad Rich Man in Hell": "Luke 16:23",
    "The Baptism of Jesus": "Matthew 3:16",
    "The Betrothed of Cana": "John 2:1",
    "The Birth of Our Lord Jesus Christ": "Luke 2:7",
    "The Blind Man Washes in the Pool of Siloam": "John 9:7",
    "The Blind and Mute Man Possessed by Devils": "Matthew 12:22",
    "The Blind in the Ditch": "Matthew 15:14",
    "The Blind of Capernaum": "Matthew 9:27-28",
    "The Body of Jesus Carried to the Anointing Stone": "John 19:39-40",
    "The Brow of the Hill near Nazareth": "Luke 4:29",
    "The Calling of Saint James and Saint John": "Matthew 4:21",
    "The Calling of Saint John and Saint Andrew": "John 1:37-40",
    "The Calling of Saint Matthew": "Matthew 9:9",
    "The Calling of Saint Peter and Saint Andrew": "Matthew 4:18",
    "The Canaanite's Daughter": "Matthew 15:22",
    "The Centurion": "Matthew 8:5",
    "The Chief Priests Ask Jesus by What Right Does He Act in This Way": "Matthew 21:23",
    "The Chief Priests Take Counsel Together": "John 11:47",
    "The Childhood of Saint John the Baptist": "Luke 1:80",
    "The Cock Crowed": "Matthew 26:74",
    "The Communion of the Apostles": "Luke 22:19",
    "The Confession of the Centurion": "Mark 15:39",
    "The Corner Stone": "Matthew 21:42",
    "The Crowd Left Calvary While Beating Their Breasts": "Luke 23:48",
    "The Crowning of Thorns": "Matthew 27:29",
    "The Daughter of Herodias Dancing": "Mark 6:22",
    "The Daughter of Jairus": "Mark 5:41",
    "The Daughters of Jerusalem": "Luke 23:28",
    "The Dead Appear in Jerusalem": "Matthew 27:52-53",
    "The Dead Appear in the Temple": "Matthew 27:52-53",
    "The Death of Jesus": "Luke 23:46",
    "The Descent from the Cross": "Mark 15:46",
    "The Disbelief of Saint Thomas": "John 20:27",
    "The Disciples Admire the Buildings of the Temple": "Mark 13:1",
    "The Disciples Eat Wheat on the Sabbath": "Matthew 12:1",
    "The Disciples Having Left Their Hiding Place Watch from Afar in Agony": "Luke 23:49",
    "The Disciples of Jesus Baptize": "John 4:2",
    "The Ear of Malchus": "John 18:10",
    "The Earthquake": "Matthew 27:51",
    "The Enemy Who Sows": "Matthew 13:25",
    "The Evil Counsel": "Matthew 26:3-4",
    "The Exhortation to the Apostles": "Matthew 10:16",
    "The False Witnesses": "Mark 14:56",
    "The First Denial of Saint Peter": "John 18:17",
    "The First Nail": "Luke 23:33",
    "The First Shall Be Last": "Matthew 20:16",
    "The Flight into Egypt": "Matthew 2:14",
    "The Flight of the Apostles": "Mark 14:50",
    "The Foal of Bethpage": "Matthew 21:2",
    "The Foolish Virgins": "Matthew 25:8",
    "The Four Guards Sat Down and Watched Him": "Matthew 27:36",
    "The Garments Divided by Cast Lots": "John 19:24",
    "The Gentiles Ask to See Jesus": "John 12:20-21",
    "The Good Samaritan": "Luke 10:33",
    "The Good Shepherd": "John 10:11",
    "The Grotto of the Agony": "Luke 22:41",
    "The Guards Falling Backwards": "John 18:6",
    "The Head of Saint John the Baptist on a Charger": "Mark 6:28",
    "The Healed Blind Man Tells His Story to the Jews": "John 9:15",
    "The Healing of Malchus": "Luke 22:51",
    "The Healing of Peter's Mother-in-law": "Mark 1:31",
    "The Healing of Ten Lepers": "Luke 17:12-14",
    "The Healing of the Officer's Son": "John 4:50",
    "The Hidden Treasure": "Matthew 13:44",
    "The Holy Women": "Luke 8:2-3",
    "The Holy Women Watch from Afar": "Mark 15:40",
    "The Jews Took Up Rocks to Stone Jesus": "John 8:59",
    "The Judgment on the Gabbatha": "John 19:13",
    "The Kiss of Judas": "Matthew 26:49",
    "The Last Supper": "Matthew 26:20",
    "The Last Supper Judas Dipping his Hand in the Dish": "Matthew 26:23",
    "The Lord Wept": "Luke 19:41",
    "The Lord's Prayer": "Matthew 6:9",
    "The Lost Drachma": "Luke 15:8",
    "The Madgalene Runs to the Cenacle to Tell the Apostles that the Body of Jesus is No Longer in the Tomb": "John 20:2",
    "The Magi Journeying": "Matthew 2:9",
    "The Magi in the House of Herod": "Matthew 2:7",
    "The Magnificat": "Luke 1:46",
    "The Man Bearing a Pitcher": "Mark 14:13",
    "The Man Who Hoards": "Luke 12:16-20",
    "The Man at the Plough": "Luke 9:62",
    "The Man with an Infirmity of Thirty-Eight Years": "John 5:5",
    "The Man with the Withered Hand": "Mark 3:5",
    "The Man with the jar of water - Tissot": "Mark 14:13",
    "The Marriage at Cana": "John 2:9",
    "The Massacre of the Innocents": "Matthew 2:16",
    "The Meal in the House of Matthew": "Matthew 9:10",
    "The Meal in the House of the Pharisee": "Luke 7:36",
    "The Merchants Chased from the Temple": "John 2:15",
    "The Message of Pilate's Wife. Pilate": "Matthew 27:19",
    "The Miracle of the Loaves and Fishes": "Matthew 14:19",
    "The Miraculous Draught of Fishes": "Luke 5:6",
    "The Morning Judgment": "Luke 22:66",
    "The Nail for the Feet": "Luke 23:33",
    "The Ointment of the Magdalene": "John 12:3",
    "The Palsied Man Let Down through the Roof": "Mark 2:4",
    "The Pardon of the Good Thief": "Luke 23:43",
    "The People Seek Jesus to Make Him King": "John 6:15",
    "The Pharisees Question Jesus": "Matthew 22:15",
    "The Pharisees and the Herodians Conspire Against Jesus": "Mark 3:6",
    "The Pharisees and the Saduccees Come to Tempt Jesus": "Matthew 16:1",
    "The Pilgrims of Emmaus on the Road": "Luke 24:15",
    "The Piscina Probatica or Pool of Bethesda": "John 5:2",
    "The Poor Lazarus at the Rich Man's Door": "Luke 16:20",
    "The Possessed Man in the Synagogue": "Mark 1:23",
    "The Presentation of Jesus in the Temple": "Luke 2:22",
    "The Primacy of Saint Peter": "John 21:17",
    "The Procession Nearing Calvary": "Luke 23:27",
    "The Procession in the Streets of Jerusalem": "Matthew 21:10",
    "The Procession of Judas": "John 18:3",
    "The Procession on the Mount of Olives": "Luke 19:37",
    "The Prodigal Son Begging": "Luke 15:16",
    "The Prophecy of the Destruction of the Temple": "Matthew 24:2",
    "The Protestations of Saint Peter": "Matthew 26:33",
    "The Raising of the Cross": "John 19:18",
    "The Repentant Mary Magdalene": "Luke 7:38",
    "The Resurrection": "Matthew 28:6",
    "The Resurrection of Lazarus": "John 11:43-44",
    "The Resurrection of the Widow's Son at Nain": "Luke 7:14",
    "The Return from Egypt": "Matthew 2:21",
    "The Return of the Prodigal Son": "Luke 15:20",
    "The Rich Young Man Went Away Sorrowful": "Matthew 19:22",
    "The Scourging on the Back": "John 19:1",
    "The Scourging on the Front": "John 19:1",
    "The Scribe Stood to Tempt Jesus": "Luke 10:25",
    "The Second Denial of Saint Peter": "John 18:25",
    "The Second Miraculous Draught of Fishes": "John 21:6",
    "The Sermon of the Beatitudes": "Matthew 5:3",
    "The Sick Awaiting the Passage of Jesus": "Matthew 14:35",
    "The Sojourn in Egypt": "Matthew 2:14-15",
    "The Son of the Vineyard": "Matthew 21:37",
    "The Sorrow of Saint Peter": "Luke 22:62",
    "The Sorrowful Mother": "John 19:25",
    "The Soul of the Good Thief": "Luke 23:43",
    "The Sower": "Matthew 13:3",
    "The Strike of the Lance": "John 19:34",
    "The Swine Driven into the Sea": "Mark 5:13",
    "The Thieves Legs Are Broken": "John 19:32",
    "The Third Denial of Peter. Jesus' Look of Reproach": "Luke 22:61",
    "The Title on the Cross": "John 19:19",
    "The Torn Cloak--Jesus Condemned to Death by the Jews": "Matthew 26:65",
    "The Tower of Siloam": "Luke 13:4",
    "The Transfiguration": "Matthew 17:2",
    "The Tribunal of Annas": "John 18:19",
    "The Tribute Money": "Matthew 22:19",
    "The Two Blind Men at Jericho": "Matthew 20:30",
    "The Two Marys Watch the Tomb": "Matthew 27:61",
    "The Two Men Possessed with Devils": "Matthew 8:28",
    "The Two Women at the Mill": "Matthew 24:41",
    "The Vase of Myrrh and Gall": "Matthew 27:34",
    "The Vine Dresser and the Fig Tree": "Luke 13:7",
    "The Vision of Saint Joseph": "Matthew 1:20",
    "The Vision of Zacharias": "Luke 1:11",
    "The Visitation": "Luke 1:40",
    "The Voice from on High": "John 12:28",
    "The Voice in the Desert": "Matthew 3:3",
    "The Washing of the Feet": "John 13:5",
    "The Watch Over the Tomb": "Matthew 27:66",
    "The Widow's Mite": "Mark 12:42",
    "The Wise Virgins": "Matthew 25:4",
    "The Woman of Samaria at the Well": "John 4:7",
    "The Woman with an Infirmity of Eighteen Years": "Luke 13:11",
    "The Woman with an Issue of Blood": "Mark 5:27",
    "The Youth of Jesus": "Luke 2:51",
    "They Dressed Him in His Own Garments": "Matthew 27:31",
    "Tissot The Pharisee and the publican Brooklyn": "Luke 18:10",
    "Tissot ten virgins": "Matthew 25:1",
    "Tissot, James - La Résurrection - 1886-1894": "Matthew 28:6",
    "Tissot-the-descent-from-the-cross": "Mark 15:46",
    "TissotAnnunciation": "Luke 1:28",
    "TissotBeatitudes": "Matthew 5:3",
    "TissotChristservedbyangels": "Matthew 4:11",
    "TissotGrotto": "Luke 22:41",
    "TissotLordsPrayer": "Matthew 6:9",
    "TissotRaisingCroos": "John 19:18",
    "TissotSalome": "Mark 6:22",
    "Touch Me Not": "John 20:17",
    "Two or Three Gathered in my Name": "Matthew 18:20",
    "What Our Lord Saw from the Cross": "Luke 23:35",
    "Asseenfromthecross-vi": "Luke 23:35",
    "With Passover Approaching, Jesus Goes Up to Jerusalem": "John 11:55",
    "Woe unto You, Scribes and Pharisees": "Matthew 23:13",
    "Woman Behold Thy Son": "John 19:26",
    "You Could Not Watch One Hour With Me": "Matthew 26:40",
    "You Follow Me for the Miracles": "John 6:26",
    "Zacchaeus in the Sycamore Awaiting the Passage of Jesus": "Luke 19:4",
    "Zacharias Killed Between the Temple and the Altar": "Matthew 23:35",
}
